In [257]:
from math import factorial 
import numpy as np


In [258]:
def test(n):
    with open ("testy/in/imp{}.in".format(n), "r") as f:
        test_in = f.read()
    with open ("testy/out/imp{}.out".format(n), "r") as f:
        test_out = f.read()
    test_in = test_in.split("\n")
    test_in[1] = test_in[1].split(" ")[:-1]
    return test_in,test_out
def test2(n):
    with open ("testy2/in/imp{}.in".format(n), "r") as f:
        test_in = f.read()
    with open ("testy2/out/imp{}.out".format(n), "r") as f:
        test_out = f.read()
    test_in = test_in.split("\n")
    test_in[1] = test_in[1].split(" ")[:-1]
    return test_in,test_out

In [259]:
def modulo(n):
    return n%1000000007
def certainties(n,t):
    if n == 3 and t[0] != t[2]:
        return False
    w = np.zeros(n)
    z = np.zeros(n)
    z[0] = 1
    z[-1] = 1
    w[1]=t[0]
    w[-2]=t[-1]
    for i in range(0,n):
        if w[i] == 0:
            if i != 0 and i != n-1:
                if t[i-1] == t[i+1]:
                    w[i] = t[i-1]
                    z[i-1] = 1
                    z[i+1] = 1
                elif w[i+2] != 0 and w[i+2] != t[i+1]:
                    w[i] = t[i+1]
                    z[i+1] = 1
                elif w[i-2] != 0 and w[i-2] != t[i-1]:
                    w[i] = t[i-1]
                    z[i-1] =1
            if i == n-1:
                if w[i-2] != 0 and w[i-2] != t[i-1]:
                    w[i] = t[i-1]
                    z[i-1] =1
            if i == 0:
                if w[i+2] != 0 and w[i+2] != t[i+1]:
                    w[i] = t[i+1]
                    z[i+1] =1
        else:
            try:
                if w[i-2] != 0 and z[i-1] == 0: 
                    return False
            except IndexError:
                pass
            try:
                if t[i-1] == w[i]:
                    z[i-1] = 1
            except IndexError:
                pass
            try:
                if t[i+1] == w[i]:
                    z[i+1] = 1
            except IndexError:
                pass
    for i in range(n-1,-1,-1):
        if w[i] == 0:
            if i != 0 and i != n-1:
                if t[i-1] == t[i+1]:
                    w[i] = t[i-1]
                    z[i-1] = 1
                    z[i+1] = 1
                elif w[i+2] != 0 and w[i+2] != t[i+1]:
                    w[i] = t[i+1]
                    z[i+1] = 1
                elif w[i-2] != 0 and w[i-2] != t[i-1]:
                    w[i] = t[i-1]
                    z[i-1] =1
            if i == n-1:
                if w[i-2] != 0 and w[i-2] != t[i-1]:
                    w[i] = t[i-1]
                    z[i-1] =1
            if i == 0:
                try:
                    if w[i+2] != 0 and w[i+2] != t[i+1] and w[i] != t[i+1]:
                        w[i] = t[i+1]
                        z[i+1] =1
                except:
                    pass
        else:
            try:
                if w[i-2] != 0 and z[i-1] == 0: 
                    return False
            except IndexError:
                pass
            try:
                if w[i+2] != 0 and z[i+1] == 0: 
                    return False
            except IndexError:
                pass
            try:
                if t[i-1] == w[i]:
                    z[i-1] = 1
            except IndexError:
                pass
            try:
                if t[i+1] == w[i]:
                    z[i+1] = 1
            except IndexError:
                pass
    
    return w,z

def daszki(n,z):
    w = []
    m = np.zeros(n)
    total = 0
    for i in range(n):
        cnt = 0
        if z[i] == 0 and m[i] != 1:
            # print("ROZPATRUJE",i)
            m[i] = 1
            cnt = 1
            total += 1
            try:
                if z[i+2] == 0:
                    # print("WIECEJ NIZ 1")
                    for j in range(i+2,n,2):
                        if z[j] == 0:
                            m[j] = 1
                            cnt += 1
                            total += 1
                        else:
                            break
            except IndexError:
                pass
            # print("APPENDING")
            w.append(cnt)
 
    return w,total
                    
def main(n,t):
    x = certainties(n,t)
    if x == False:
        return 0
    w,z = x
    d,total_zero = daszki(n,z)
    q =np.count_nonzero(w==0)
    scale = 1
    increment = 1
    last_factorial = factorial(q-total_zero)
    for i in d:
        for j in range(1,i+1):
            scale += increment
            # print(i,j,scale)
        increment = scale
    output = modulo(modulo(scale) * modulo(last_factorial))
    # print(modulo(scale),modulo(last_factorial))
    return modulo(output),w,z

In [260]:
cnt = 0
while 1:
    res = test2(cnt)
    n = int(res[0][0])
    t = [int(x) for x in res[0][1]]
    test_out = res[1]
    output = main(n,t)
    if output == False:
        if(int(output) != int(test_out)):
            print(cnt,output,test_out.split("\n")[0])
    else:
        output = output[0]
        if(int(output) != int(test_out)):
            print(cnt,output,test_out.split("\n")[0])
    cnt += 1


2 165741929 841293349
3 87731709 87642
4 947855262 762862784
5 889278622 533850354
6 199423545 700996292
7 846216043 895926493


KeyboardInterrupt: 

In [ ]:
for i in range(1,57):
    res = test(i)
    n = int(res[0][0])
    t = [int(x) for x in res[0][1]]
    test_out = res[1]
    output = main(n,t)
    if output == False and test_out != "0":
        print(i,output,test_out,n,t)
    elif output != False:
        output,w,z = output
        if(int(output) != int(test_out)):
            print(i,output,test_out)
            print(t)
            print(w)
            print(z)


4 0 3 5 [1, 5, 4, 3, 4]
15 2 0
[16, 14, 2, 9, 10, 11, 4, 15, 4, 12, 4, 1, 13, 3, 13, 5]
[14. 16.  9.  2. 11. 10. 15.  4. 12.  4.  1.  0.  3. 13.  5.  0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
16 54 0
[15, 12, 17, 14, 7, 1, 7, 1, 7, 8, 10, 8, 6, 13, 3, 2, 9]
[ 0. 15.  0. 17.  0.  7.  1.  7.  0. 10.  8.  6.  0.  3.  0.  9.  0.]
[1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1.]
29 0 6 11 [7, 8, 11, 1, 9, 6, 5, 4, 2, 3, 2]
