In [3]:
from math import factorial 
import numpy as np
from itertools import permutations

In [4]:
def test(n):
    with open ("testy/in/imp{}.in".format(n), "r") as f:
        test_in = f.read()
    with open ("testy/out/imp{}.out".format(n), "r") as f:
        test_out = f.read()
    test_in = test_in.split("\n")
    test_in[1] = test_in[1].split(" ")[:-1]
    return test_in,test_out


In [7]:
def perm(n,a,indexes):
    cnt=0
    for i in indexes:
        a[i] = n[cnt]
        cnt = cnt+1
    return a

def lc(n,t):
    for i in range(len(t)):
        if i == 0:
            if t[i] != n[i+1]:
                return False
        if i == len(t)-1:
            if t[i] != n[i-1]:
                return False
        else:
            if t[i] != n[i-1] and t[i] != n[i+1]:
                return False
    return True
def brute (x):
    res = test(x)
    n = int(res[0][0])
    t = [int(x) for x in res[0][1]]
    test_out = res[1]
    w = np.zeros(n)
    w[1]=t[0]
    w[-2]=t[-1]
    for i in range(0,n):
        if w[i] == 0:
            if i != 0 and i != n-1:
                if t[i-1] == t[i+1]:
                    w[i] = t[i-1]
                elif w[i+2] != 0 and w[i+2] != t[i+1]:
                    w[i] = t[i+1]
                elif w[i-2] != 0 and w[i-2] != t[i-1]:
                    w[i] = t[i-1]
            if i == n-1:
                if w[i-2] != 0 and w[i-2] != t[i-1]:
                    w[i] = t[i-1]
    for i in range(n-1,-1,-1):
        if w[i] == 0:
            if i != 0 and i != n-1:
                if t[i-1] == t[i+1]:
                    w[i] = t[i-1]
                elif w[i+2] != 0 and w[i+2] != t[i+1]:
                    w[i] = t[i+1]
                elif w[i-2] != 0 and w[i-2] != t[i-1]:
                    w[i] = t[i-1]
            if i == n-1:
                if w[i-2] != 0 and w[i-2] != t[i-1]:
                    w[i] = t[i-1]
    print(t,test_out)
    print(w)
    print()
    arr = np.arange(1,n+1)
    for element in w:
        if element in arr:
            arr = np.delete(arr,np.argwhere(arr == int(element)))
    cnt = 0
    indexes = np.argwhere(w == 0)
    distribution = np.zeros((n,n))
    distribution2 = np.zeros((n,n))
    distribution3 = np.zeros((n,n))
    distribution4 = np.zeros((n,n))
    for i in permutations(arr):
        p = perm(i,w,indexes)
        if lc(p,t):
            print(p)
            for x in range(len(p)):
                distribution[int(p[x]-1)][x] += 1
            cnt += 1
    print("CNT",cnt)
    # PD(distribution,n)   
    print(distribution)
    
def PD(d,n):
    for i in range(n):
        print(i+1)
        for j in range(n):
            if d[j][i]!=0:
                print(j+1,"-",int(d[j][i]),end="  ")
        print()
            

In [8]:
brute(12)

[11, 1, 13, 3, 13, 12, 6, 12, 2, 4, 9, 5, 10] 18
[ 0. 11.  0. 13.  0.  6. 12.  2.  0.  9.  0. 10.  0.]

[ 1. 11.  3. 13.  7.  6. 12.  2.  4.  9.  5. 10.  8.]
[ 1. 11.  3. 13.  7.  6. 12.  2.  4.  9.  8. 10.  5.]
[ 1. 11.  3. 13.  7.  6. 12.  2.  8.  9.  4. 10.  5.]
[ 1. 11.  3. 13.  8.  6. 12.  2.  4.  9.  5. 10.  7.]
[ 1. 11.  3. 13.  8.  6. 12.  2.  4.  9.  7. 10.  5.]
[ 1. 11.  3. 13.  8.  6. 12.  2.  7.  9.  4. 10.  5.]
[ 1. 11.  7. 13.  3.  6. 12.  2.  4.  9.  5. 10.  8.]
[ 1. 11.  7. 13.  3.  6. 12.  2.  4.  9.  8. 10.  5.]
[ 1. 11.  7. 13.  3.  6. 12.  2.  8.  9.  4. 10.  5.]
[ 1. 11.  8. 13.  3.  6. 12.  2.  4.  9.  5. 10.  7.]
[ 1. 11.  8. 13.  3.  6. 12.  2.  4.  9.  7. 10.  5.]
[ 1. 11.  8. 13.  3.  6. 12.  2.  7.  9.  4. 10.  5.]
[ 7. 11.  1. 13.  3.  6. 12.  2.  4.  9.  5. 10.  8.]
[ 7. 11.  1. 13.  3.  6. 12.  2.  4.  9.  8. 10.  5.]
[ 7. 11.  1. 13.  3.  6. 12.  2.  8.  9.  4. 10.  5.]
[ 8. 11.  1. 13.  3.  6. 12.  2.  4.  9.  5. 10.  7.]
[ 8. 11.  1. 13.  3.  6. 12.  2.